#!/bin/bash

packageName=$(grep '^name:' pubspec.yaml | awk '{print $2}');

cd lib
#echo "library ${packageName};" > package_temp.dart
#echo "" >> package_temp.dart

cd src
while IFS= read -r line; do
    # Remove the leading "./" from the file path
    modified_line=${line#./}
    echo "export 'package:${packageName}/src/${modified_line}';"
done < <(find . -type f -name "*.dart") >> ../package_temp.dart
cd ../
mv package_temp.dart "${packageName}".dart

echo "Generated exports successfully"
